### ISSUE TITLE
[IDE] git 관련 기능 구현

### ISSUE THREAD

**Issue by DevrisOfStar** [SciosDevelopment/Tora#31]
# Description

IDE에서 사용하는 Git 관련 기능을 구현한다. 구현은 작성순서대로 진행한다.

# To-do

- [ ]  유저 github 아이디 업데이트
    
    → 깃허브 앱 설치 페이지로 redirect하는 부분을 구현하고 api를 통해 백엔드로 전달
    
- [ ]  깃허브에서 프로젝트 Clone

- [ ]  깃허브에서 File Pull
    
     → branch를 지정하기 전에 main으로 테스트
    
- [ ]  깃허브에 Push
    
     → branch를 지정하기 전에 main으로 테스트
