### ISSUE TITLE
[Project] 프로젝트 관련 기능 구현

### ISSUE THREAD

**Issue by DevrisOfStar** [SciosDevelopment/Tora#32]
# Description
### NewProjectPopup
 - 프로젝트 생성 (Post projects/create) : Popup에 설정된 데이터를 이용하여 프로젝트를 생성
 
### OpenSource
- 프로젝트 리스트 가져오기 (Post /projects) : Post Load 방식과 반대로 가져온 데이터를 모두 state로 저장한상태로 두고, Filter를 사용. (params로 Filter x)
    → 새로고침이 필요없고, 필터에 의해서 데이터를 로드함 (서버에 한번만 접근하면 됨)   
    → 이부분에 대한 로직 변경이 필요함
    

### Project

- 프로젝트 상세보기 (Get project/:id) : Project/Main에 정보를 보여줌 (사이드 부분)
- 프로젝트 ReadMe File 불러오기 : post projects/:id/directory/read를 이용하여 불러오기 (폴더 경로 입력 혹은 최상위폴더로 지정)
    → Readme file이 없는 경우, -정보없음- 으로 나타냄
    
- 프로젝트 feed부분 : Project 상세보기에 현재 feed 정보가 없으므로 Component 형태를 수정
      → 하드코딩으로 되어있는 feed 부분을 Chain 형태로 조정 
      → 데이터 구조 및 feed 종류가 정해지면 작업할 예정
   

# To-do
- [ ]  OpenSource Page에서 프로젝트 리스트 가져오기 (키워드 검색까지 구현)
- [ ]  프로젝트 생성 팝업에 프로젝트 생성 기능 삽입 (Import 제외)
- [ ]  프로젝트 메인페이지에 프로젝트 상세보기를 이용하여 프로젝트 정보 보여주기
- [ ]  프로젝트 파일리스트 불러오기 (Sidebar)
